export const CHANGE_BANNERS = "CHANGE_BANNERS"
export const CHANGE_HOTRECOMMEND = "CHANGE_HOTRECOMMEND"
export const CHANGE_NEWABLBUM = "CHANGE_NEWABLBUM"

export const CHANGE_UP_RANKING = "recommend/CHANGE_UP_RANKING"
export const CHANGE_NEW_RANKING = "recommend/CHANGE_New_RANKING"
export const CHANGE_ORIGIN_RANKING = "recommend/CHANGE_ORIGIN_RANKING"
